service: virtwallet-transaction-loader

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:stage, 'eu-west-1'}
  stackTags:
    Project: virtwallet
    Service: transaction-loader

custom:
  userFilesBucket: ${file(../../config.${self:provider.stage}.yml):userFilesBucket}

package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    - test/**
    - '*.yml'
    - '*.json'

functions: ${file(./sls-functions.yml)}
plugins:
  - serverless-iam-roles-per-function