service: virtwallet-account-change-set

frameworkVersion: 1.83.1

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:stage, 'eu-west-1'}
  stackTags:
    Project: virtwallet
    Service: account-change-set

package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    - test/**
    - '*.yml'
    - '*.json'

functions: ${file(./sls-functions.yml)}
plugins:
  - serverless-iam-roles-per-function