service: virtwallet-account

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:stage, 'eu-west-1'}
  apiGateway:
    restApiId:
      'Fn::ImportValue': Virtwallet-${self:provider.stage}-RestApiId
    restApiRootResourceId:
      'Fn::ImportValue': Virtwallet-${self:provider.stage}-RootResourceId
  stackTags:
    Project: virtwallet
    Service: account

custom:
  restApiAuthorizerId: '${cf:virtwallet-resources-${self:provider.stage}.VirtwalletRestApiAuthorizerId}'
  cors: '${file(../../config.${self:provider.stage}.yml):cors}'

package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    - test/**
    - '*.yml'
    - '*.json'

functions: ${file(./sls-functions.yml)}
plugins:
  - serverless-iam-roles-per-function

resources:
  Outputs:
    ApiGatewayAccountResourceId:
      Description: Id of '/account' resource created
      Value: !Ref ApiGatewayResourceAccount
      Export:
        Name: Virtwallet-${self:provider.stage}-ApiGatewayAccountResourceId
    ApiGatewayAccountAccountIdVarResourceId:
      Description: Id of '/account/{accountId}' resource created
      Value: !Ref ApiGatewayResourceAccountAccountidVar
      Export:
        Name: Virtwallet-${self:provider.stage}-ApiGatewayAccountAccountIdVarResourceId