service: virtwallet

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:stage, 'eu-west-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/virtwallet"
    - Effect: Allow
      Action: 
        - sqs:SendMessage
        - sqs:ReceiveMessage
      Resource: "*"
    - Effect: Allow
      Action: 
        - s3:GetObject
      Resource: "arn:aws:s3:::*"
  stackTags:
    Project: virtwallet

custom:
  cognitoIdpArn: ${file(./config.${self:provider.stage}.yml):cognitoIdpArn}

package:
  excludeDevDependencies: true
  individually: true

functions:
  account:
    handler: src/lambdas/account/accountLambda.handle
    events:
      - http:
          path: account
          method: post
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
      - http:
          path: account
          method: get
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
      - http:
          path: account/{accountId}
          method: get
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
      - http:
          path: account/{accountId}
          method: put
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
      - http:
          path: account/{accountId}
          method: delete
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
    package:
      include:
        - src/lambdas/account/**
        - src/libs/*
        - node_modules/**
      exclude:
        - test/**
        - .git/**
        - .travis.yml
  wallet:
    handler: src/lambdas/wallet/walletLambda.handle
    events:
      - http:
          path: account/{accountId}/wallet
          method: get
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
      - http:
          path: account/{accountId}/wallet
          method: POST
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
      - http:
          path: account/{accountId}/wallet/{walletId}
          method: GET
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
      - http:
          path: account/{accountId}/wallet/{walletId}
          method: PUT
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
      - http:
          path: account/{accountId}/wallet/{walletId}
          method: DELETE
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
    package:
      include:
        - src/lambdas/wallet/**
        - libs/*
        - node_modules/**
      exclude:
        - test/**
        - .git/**
        - .travis.yml
  transaction:
    handler: src/lambdas/transaction/transactionLambda.handle
    events:
      - http:
          path: account/{accountId}/wallet/{walletId}/transaction
          method: GET
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
      - http:
          path: account/{accountId}/wallet/{walletId}/transaction
          method: PUT
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
            querystrings:
              from: false
              to: false
      - http:
          path: account/{accountId}/wallet/{walletId}/transaction
          method: DELETE
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
      - http:
          path: account/{accountId}/wallet/{walletId}/transaction/{transactionId}
          method: GET
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
              transactionId: true
      - http:
          path: account/{accountId}/wallet/{walletId}/transaction/{transactionId}
          method: PUT
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
              transactionId: true
      - http:
          path: account/{accountId}/wallet/{walletId}/transaction/{transactionId}
          method: DELETE
          authorizer:
            arn: ${self:custom.cognitoIdpArn}
            scopes:
              - email
          parameters:
            paths:
              accountId: true
              walletId: true
              transactionId: true
    package:
      include:
        - src/lambdas/transaction/**
        - libs/*
        - node_modules/**
      exclude:
        - test/**
        - .git/**
        - .travis.yml
  fileRouter:
    handler: src/lambdas/file-router/fileRouterLambda.handle
    environment:
      ulster_csv:
        Ref: UlsterCsvParserSQSQueue
    events:
      - s3:
          bucket: virtwallet-user-files
          event: s3:ObjectCreated:*
          rules:
            - prefix: account-files/
    package:
      include:
        - src/lambdas/file-router/**
        - libs/*
        - node_modules/**
      exclude:
        - test/**
        - .git/**
        - .travis.yml
  ulsterCsvFileParser:
    handler: src/lambdas/ulster-statement-csv-parser/ulsterStatementCsvParserLambda.handle
    environment:
      transaction_queue_url:
        Ref: TransactionsSQSQueue
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UlsterCsvParserSQSQueue
              - Arn
    package:
      include:
        - src/lambdas/ulster-statement-csv-parser/**
        - libs/*
        - node_modules/**
      exclude:
        - test/**
        - .git/**
        - .travis.yml
resources:
  Resources:
    UlsterCsvParserSQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: UlsterCsvParserQueue
    TransactionsSQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: TransactionsQueue
plugins:
  - serverless-mocha-plugin
